"""Generate per-daemon README.md files (and a daemons/ index) from each daemon's
committed metadata — daemon.toml + skill/SKILL.md only, never machine-local files.

Run `python -m daimon.gen_docs` (or `make docs`) to write them; `--check` verifies
they are up to date (used by tests/CI) and exits non-zero on drift."""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

INSTALL_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(INSTALL_ROOT / "lib"))

import config  # noqa: E402
import schedule_fmt  # noqa: E402

BANNER = "<!-- Generated by `make docs` from daemon.toml + skill/SKILL.md. Do not edit by hand. -->"


def _frontmatter(text: str) -> dict[str, str]:
    if not text.startswith("---"):
        return {}
    _, fm, _ = text.split("---", 2)
    out: dict[str, str] = {}
    for line in fm.strip().splitlines():
        key, sep, val = line.partition(":")
        if sep:
            out[key.strip()] = val.strip()
    return out


def _input_comments(toml_text: str) -> dict[str, str]:
    """Map each [inputs] key to the contiguous `# comment` lines above it."""
    out: dict[str, str] = {}
    buf: list[str] = []
    in_inputs = False
    for line in toml_text.splitlines():
        s = line.strip()
        if s.startswith("[") and s.endswith("]"):
            in_inputs, buf = s == "[inputs]", []
        elif in_inputs and s.startswith("#"):
            buf.append(s.lstrip("#").strip())
        elif in_inputs and "=" in s:
            out[s.split("=", 1)[0].strip()] = " ".join(buf)
            buf = []
        elif not s:
            buf = []
    return out


def _fmt(v) -> str:
    if isinstance(v, bool):
        return f"`{str(v).lower()}`"
    if isinstance(v, list):
        return ", ".join(f"`{x}`" for x in v) if v else "—"
    return f"`{v}`" if v != "" else "—"


def _meta_lines(daemon: dict) -> list[str]:
    specs = config.sources_of(daemon)
    src = ", ".join(f"{s['name']}{' (read-write)' if s['write'] else ''}" for s in specs) or "none"
    req = ", ".join(f"`{k}`" for k in daemon.get("required_inputs", []) or []) or "none"
    lines = [
        f"- **Command:** `{daemon.get('command', '')}`",
        f"- **Schedule:** {schedule_fmt.display(daemon['schedule'])}",
        f"- **Source:** {src}",
        f"- **Required inputs:** {req}",
    ]
    if "backend" in daemon:
        lines.append(f"- **Backend:** `{daemon['backend']}`")
    return lines


def _inputs_table(inputs: dict, comments: dict[str, str]) -> list[str]:
    if not inputs:
        return ["_No daemon-specific inputs (profile defaults apply)._"]
    rows = ["| Input | Default | Notes |", "|-------|---------|-------|"]
    rows += [f"| `{k}` | {_fmt(v)} | {comments.get(k, '')} |" for k, v in inputs.items()]
    return rows


def render_daemon(ddir: Path) -> str:
    toml_text = (ddir / "daemon.toml").read_text()
    raw = tomllib.loads(toml_text)
    daemon, inputs = raw.get("daemon", {}), raw.get("inputs", {})
    fm = _frontmatter((ddir / "skill" / "SKILL.md").read_text())
    parts = [
        BANNER,
        f"# {fm.get('name', ddir.name)}",
        fm.get("description", ""),
        "\n".join(_meta_lines(daemon)),
        "## Inputs",
        "\n".join(_inputs_table(inputs, _input_comments(toml_text))),
        "## Gate",
        "`discover.sh` decides whether the daemon fires on a given run.",
        "See [skill/SKILL.md](skill/SKILL.md) for the full prompt.",
    ]
    return "\n\n".join(parts) + "\n"


def render_index(daemons: list[tuple[str, dict, dict]]) -> str:
    rows = ["| Daemon | Schedule | Description |", "|--------|----------|-------------|"]
    for slug, daemon, fm in daemons:
        sched = schedule_fmt.display(daemon["schedule"])
        rows.append(f"| [{slug}]({slug}/) | {sched} | {fm.get('description', '')} |")
    body = [
        BANNER,
        "# Daemons",
        "\n".join(rows),
        "See [../docs/writing-a-daemon.md](../docs/writing-a-daemon.md) to add one.",
    ]
    return "\n\n".join(body) + "\n"


def _targets(root: Path) -> list[tuple[Path, str]]:
    dirs = sorted(p.parent for p in (root / "daemons").glob("*/daemon.toml"))
    out = [(d / "README.md", render_daemon(d)) for d in dirs]
    index = [
        (
            d.name,
            tomllib.loads((d / "daemon.toml").read_text()).get("daemon", {}),
            _frontmatter((d / "skill" / "SKILL.md").read_text()),
        )
        for d in dirs
    ]
    out.append((root / "daemons" / "README.md", render_index(index)))
    return out


def main(argv: list[str]) -> int:
    check = "--check" in argv
    stale = []
    for path, content in _targets(INSTALL_ROOT):
        current = path.read_text() if path.exists() else None
        if current == content:
            continue
        stale.append(str(path.relative_to(INSTALL_ROOT)))
        if not check:
            path.write_text(content)
    if check and stale:
        print("stale daemon docs (run `make docs`):", *stale, sep="\n  ", file=sys.stderr)
        return 1
    print(f"{'checked' if check else 'wrote'} {len(_targets(INSTALL_ROOT))} docs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
